# Generated by Django 4.1.2 on 2022-10-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetails', '0002_employees_description_employees_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
